### ISSUE TITLE
unexpected status 1 was not ignored

### ISSUE THREAD

**Issue by raldponsua** [googlegenomics/gcp-variant-transforms#578] opened 2020-04-14 10:00 UTC
Hi, i got this error 
![varianttool error](https://user-images.githubusercontent.com/40007675/79210889-0f887d80-7e78-11ea-9448-7a97ead95013.PNG)
everytime i run from the script:
[script.sh.txt](https://github.com/googlegenomics/gcp-variant-transforms/files/4474513/script.sh.txt)

This is also what i see in the activity log
[activity log.txt](https://github.com/googlegenomics/gcp-variant-transforms/files/4474561/activity.log.txt)

**Comment by samanvp** [comment] 2020-04-14 13:00
Would it be possible to share with us the `runner_logs_20200414_092919.log`. In that screenshot you shared, if you read further you should see a message that shows where the runner log has been copied.

**Comment by samanvp** [comment] 2020-04-14 15:15
One minor issue in your `script.sh`:
You set this variable:
`TEMP_ZONE=europe-west1-b`
but later in your `docker run ...` command you don't use it. I think this will be the correct way to use that zone value:
```
docker run -v ~/.config:/root/.config \
    gcr.io/cloud-lifesciences/gcp-variant-transforms \
    --project "${GOOGLE_CLOUD_PROJECT}" \
    --zones "${TEMP_ZONE}"\
    "${COMMAND}"
```

**Comment by raldponsua** [comment] 2020-04-14 15:34
> One minor issue in your `script.sh`:
> You set this variable:
> `TEMP_ZONE=europe-west1-b`
> but later in your `docker run ...` command you don't use it. I think this will be the correct way to use that zone value:
> 
> ```
> docker run -v ~/.config:/root/.config \
>     gcr.io/cloud-lifesciences/gcp-variant-transforms \
>     --project "${GOOGLE_CLOUD_PROJECT}" \
>     --zones "${TEMP_ZONE}"\
>     "${COMMAND}"
> ```

Thanks @samanvp , i removed the variable but i still got the same error

**Comment by samanvp** [comment] 2020-04-14 15:59
The only way we could help you debug the problem is to investigate `runner_log_....` file. Could you please share that file with us?

**Comment by tneymanov** [comment] 2020-04-14 17:29
Hi @raldponsua,

Do you have an available pipeline operation log ID? It should pop up in your logs and have the following format:

`'projects/{PROJECT_ID}/locations/{REGION}/operation/{OPERATION_ID}'`

If you could provide us the above ID, it would help us debug the issue you are facing.

Thanks,
Tural

**Comment by samanvp** [comment] 2020-04-20 04:42
@raldponsua please let us know if there is a way we could help you with debugging this issue. I am going to close this but feel free to continue commenting until this is resolved.

**Closed by samanvp** 2020-04-20 04:42 UTC
